FROM bitnami/laravel:5

WORKDIR /app

# https://stackoverflow.com/questions/76094428/debian-stretch-repositories-404-not-found
RUN echo 'deb http://archive.debian.org/debian stretch main' | sudo tee /etc/apt/sources.list
RUN echo 'deb http://archive.debian.org/debian-security/ stretch/updates main' | sudo tee -a /etc/apt/sources.list

RUN sudo apt-get update -qq && \
    sudo apt-get install -y git python build-essential

COPY . /app
RUN sudo chown -R bitnami:bitnami .
RUN composer install
